language: cpp

compiler: g++

branches:
  - master

addons:
  apt:
    sources:
    - geant4
    - sourceline: 'deb http://lcg-heppkg.web.cern.ch/lcg-heppkg/debian stable hep'
    - sourceline: 'deb-src http://lcg-heppkg.web.cern.ch/lcg-heppkg/debian stable hep'
    packages:
    - cmake
    - geant4


before_script:
  - set -e
  - ls
  - mkdir build
  - cd build
  - cmake .. 
  - set +e

script:
  - ls
  - make
